name: Conventional Pull Request

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: CondeNast/conventional-pull-request-action@v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Configure which types are allowed (optional)
          # The types should match the ones from commitizen when the PR is created using it.
          # Default: https://github.com/commitizen/conventional-commit-types/blob/master/index.json
          commitTypes: |
            fix
            feat
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          # Configure which scopes are allowed (optional).
          # These are regex patterns auto-wrapped in `^ $`.
          # scopes: |
          #   core
          #   ui
          #   .*
          # Configure that a scope must always be provided (optional).
          # scopes: false
          # Configure additional validation for the subject based on a regex.
          # This example ensures the subject doesn't start with an uppercase character.
          # subjectPattern: ^(?![A-Z]).+$
          # If `subjectPattern` is configured, you can use this property to override
          # the default error message that is shown when the pattern doesn't match.
          # subjectPatternError: |
          #   The subject "{subject}" found in the pull request title "{title}"
          #   didn't match the configured pattern. Please ensure that the subject
          #   doesn't start with an uppercase character.